[tools]
go = "1.25"
helm = "4.1.4"
helmfile = "1.4.4"
sops = "3.12.2"
golangci-lint = "2.11"
pre-commit = "4.6.0"
kubectl = "1.36.0"
stern = "1.31.0"

[tool_alias]
kubectl = "aqua:kubernetes/kubernetes/kubectl"
stern = "aqua:stern/stern"

[env]
GOFLAGS = "-count=1"

[hooks]
postinstall = [
    "helm plugin install https://github.com/jkroepke/helm-secrets/releases/download/v4.7.4/secrets-4.7.4.tgz --verify=false 2> /dev/null || true",
    "helm plugin install https://github.com/jkroepke/helm-secrets/releases/download/v4.7.4/secrets-getter-4.7.4.tgz --verify=false 2> /dev/null || true",
    "helm plugin install https://github.com/jkroepke/helm-secrets/releases/download/v4.7.4/secrets-post-renderer-4.7.4.tgz --verify=false 2> /dev/null || true",
    "helm plugin install https://github.com/databus23/helm-diff --verify=false 2> /dev/null || true",
    "helm plugin install https://github.com/helm-unittest/helm-unittest 2> /dev/null || true",
]
