apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tatara-memory.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tatara-memory.labels" . | nindent 4 }}
data:
  {{- include "tatara-memory.envConfig" . | nindent 2 }}
