apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lightrag.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
data:
  {{- include "lightrag.configKeys" . | nindent 2 }}
